title = "My Page "

baseURL = "https://geekabhinav007.github.io/www"
publishDir = "docs"

languageCode = "en-us"
theme = "ananke"
themesDir = "themes"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Master trainer: Empowering Folk"
  facebook = ""
  twitter = "https://twitter.com/geek_abhinav/"
  instagram = "https://www.instagram.com/_i_abhi.nav/"
  youtube = ""
  github = "https://github.com/geekabhinav007"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/kumar-abhinav-596b27188/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  
  background_color_class = "bg-blue"
  featured_image = "https://specials-images.forbesimg.com/imageserve/5f1bb34ef850f97f3e202c56/960x0.jpg?fit=scale"
  recent_posts_number = 2
